const neutralCanvas = '#FBF7F1';
const neutralCanvasSoft = '#F4EEE4';
const neutralCanvasStrong = '#E8DFD2';
const neutralCanvasDeep = '#09111F';
const neutralPanel = '#FFFDFC';
const neutralPanelMuted = '#FBF7F2';
const neutralPanelRaised = '#FFFEFD';
const neutralSeparator = 'rgba(150, 128, 98, 0.20)';
const neutralSeparatorStrong = 'rgba(121, 98, 70, 0.28)';
const neutralHairline = 'rgba(160, 137, 106, 0.14)';
const neutralShadow = '#0F172A';

export const colors = {
  bg: neutralCanvas,
  bgSoft: neutralCanvasSoft,
  bgStrong: neutralCanvasStrong,
  bgTint: '#FFF9F3',
  bgDeep: neutralCanvasDeep,
  heroBackdropStart: '#09111F',
  heroBackdropMid: '#14233F',
  heroBackdropEnd: '#2A4B7E',
  heroGlow: 'rgba(214, 158, 46, 0.14)',
  heroGlowSoft: 'rgba(255, 255, 255, 0.10)',
  panel: neutralPanel,
  panelAlt: neutralPanelMuted,
  surface: neutralPanel,
  surfaceMuted: '#FBF7F2',
  surfaceRaised: neutralPanelRaised,
  surfaceHero: '#FFFDFB',
  surfaceElevated: '#FFFDFC',
  surfaceGlass: 'rgba(255, 255, 255, 0.14)',
  surfaceGlassStrong: 'rgba(255, 255, 255, 0.20)',
  card: neutralPanel,
  cardMuted: '#FAFBFD',
  overlay: 'rgba(9, 17, 31, 0.28)',
  overlayStrong: 'rgba(9, 17, 31, 0.42)',
  primary: '#2F6FED',
  primarySoft: '#EAF1FF',
  primaryStrong: '#153E8A',
  accent: '#5B8DEF',
  accentSoft: '#F2E9DA',
  accentStrong: '#1D4AA6',
  text: '#102033',
  textStrong: '#09111C',
  textSoft: '#33445E',
  textPrimary: '#09111C',
  textSecondary: '#33445E',
  textInverse: '#FFFFFF',
  textInverseSoft: 'rgba(255, 255, 255, 0.78)',
  muted: '#66768D',
  mutedSoft: '#8A97AA',
  mutedInverse: 'rgba(255, 255, 255, 0.62)',
  subtle: '#95A3B6',
  danger: '#C83A3A',
  dangerSoft: '#FCEEEE',
  dangerStrong: '#8D2323',
  warning: '#B7791F',
  warningSoft: '#FFF4E0',
  warningStrong: '#8A5511',
  success: '#1D7C5B',
  successSoft: '#E5F4EE',
  successStrong: '#115740',
  info: '#295DCC',
  infoSoft: '#E8F0FF',
  infoStrong: '#1F4A9B',
  border: '#E5D8C5',
  borderStrong: '#D4C2A9',
  borderInverse: 'rgba(255, 255, 255, 0.24)',
  separator: neutralSeparator,
  separatorStrong: neutralSeparatorStrong,
  separatorInverse: 'rgba(255, 255, 255, 0.16)',
  hairline: neutralHairline,
  slate900: '#0F172A',
  slate700: '#334155',
  sky500: '#0EA5E9',
  violet500: '#8B5CF6',
  emerald500: '#10B981',
  shadow: neutralShadow,
};

export const dashboardThemeModes = Object.freeze(['midnight', 'light']);

export const dashboardThemes = {
  midnight: {
    mode: 'midnight',
    label: 'Midnight',
    statusBarStyle: 'light-content',
    chromeGradient: ['#09111F', '#14233F', '#1F3B67'],
    colors: {
      bg: '#08111F',
      bgSoft: '#0D1A2D',
      bgStrong: '#142746',
      surface: 'rgba(9, 17, 31, 0.74)',
      surfaceRaised: 'rgba(15, 28, 49, 0.94)',
      surfaceMuted: 'rgba(255, 255, 255, 0.08)',
      card: 'rgba(15, 28, 49, 0.92)',
      border: 'rgba(255, 255, 255, 0.12)',
      borderStrong: 'rgba(255, 255, 255, 0.20)',
      text: '#E6EDF7',
      textStrong: '#FFFFFF',
      textSoft: '#C1CFE2',
      muted: '#9FB2CA',
      mutedSoft: '#D6DFEC',
      overlay: 'rgba(2, 6, 23, 0.58)',
      button: 'rgba(255, 255, 255, 0.08)',
      buttonStrong: '#FFFFFF',
      buttonStrongText: '#09111F',
      indicator: '#7DB2FF',
    },
  },
  light: {
    mode: 'light',
    label: 'Light',
    statusBarStyle: 'dark-content',
    chromeGradient: ['#FFFFFF', '#F7F8FA', '#EEF3F8'],
    colors: {
      bg: '#FFFFFF',
      bgSoft: '#F7F8FA',
      bgStrong: '#EEF3F8',
      surface: 'rgba(255, 255, 255, 0.96)',
      surfaceRaised: '#FFFFFF',
      surfaceMuted: '#F3F6FA',
      card: '#FFFFFF',
      border: '#D8E2EC',
      borderStrong: '#C7D3E0',
      text: '#1E293B',
      textStrong: '#0F172A',
      textSoft: '#475569',
      muted: '#64748B',
      mutedSoft: '#94A3B8',
      overlay: 'rgba(15, 23, 42, 0.22)',
      button: '#F8FAFC',
      buttonStrong: '#0F172A',
      buttonStrongText: '#FFFFFF',
      indicator: '#2F6FED',
    },
  },
};

export const spacing = {
  xxs: 4,
  xs: 6,
  sm: 10,
  md: 14,
  lg: 20,
  xl: 28,
  xxl: 36,
};

export const radii = {
  sm: 10,
  md: 14,
  lg: 20,
  xl: 28,
  pill: 999,
};

export const motion = {
  fast: 180,
  normal: 260,
  slow: 420,
  gentle: 320,
  emphasis: 220,
  spring: {
    stiffness: 190,
    damping: 18,
    mass: 0.95,
  },
};

export const shadows = {
  card: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 4,
  },
  floating: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 8,
  },
  hero: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 36,
    elevation: 12,
  },
};

function makeRoleTheme(overrides) {
  return {
    bg: colors.bg,
    bgSoft: colors.bgSoft,
    bgStrong: colors.bgStrong,
    surface: colors.surface,
    surfaceMuted: colors.surfaceMuted,
    surfaceRaised: colors.surfaceRaised,
    surfaceElevated: colors.surfaceElevated,
    surfaceTint: colors.bgTint,
    surfaceGlass: colors.surfaceGlass,
    surfaceGlassStrong: colors.surfaceGlassStrong,
    card: colors.card,
    cardMuted: colors.cardMuted,
    borderSoft: colors.hairline,
    borderStrong: colors.borderStrong,
    separator: colors.separator,
    separatorStrong: colors.separatorStrong,
    text: colors.text,
    textStrong: colors.textStrong,
    textSoft: colors.textSoft,
    muted: colors.muted,
    mutedSoft: colors.mutedSoft,
    subtle: colors.subtle,
    chip: colors.surfaceMuted,
    chipText: colors.textSoft,
    focusRing: colors.primarySoft,
    shadow: colors.shadow,
    border: colors.border,
    ...overrides,
  };
}

export const roleThemes = {
  student: makeRoleTheme({
    bg: '#F1F7FE',
    bgSoft: '#E1EEFD',
    bgStrong: '#D1E5FC',
    accent: '#0EA5E9',
    accentSoft: '#E0F2FE',
    accentStrong: '#0369A1',
    highlight: '#F59E0B',
    highlightSoft: '#FEF3C7',
    surface: '#FFFFFF',
    surfaceMuted: '#F8FAFC',
    surfaceRaised: '#FCFDFF',
    surfaceTint: '#F0F9FF',
    surfaceSoft: '#E0F2FE',
    surfaceGlow: 'rgba(14, 165, 233, 0.12)',
    border: '#D1E5FC',
    borderStrong: '#BAE6FD',
    borderSoft: 'rgba(14, 165, 233, 0.10)',
    separator: 'rgba(14, 165, 233, 0.12)',
    separatorStrong: 'rgba(14, 165, 233, 0.20)',
    chip: '#E0F2FE',
    chipText: '#0369A1',
  }),
  parent: makeRoleTheme({
    bg: '#FEF9F1',
    bgSoft: '#FDF2E1',
    bgStrong: '#FCEBD1',
    accent: '#F59E0B',
    accentSoft: '#FEF3C7',
    accentStrong: '#B45309',
    highlight: '#0EA5E9',
    highlightSoft: '#E0F2FE',
    surface: '#FFFFFF',
    surfaceMuted: '#FFFBF5',
    surfaceRaised: '#FFFEFC',
    surfaceTint: '#FFFBEB',
    surfaceSoft: '#FEF3C7',
    surfaceGlow: 'rgba(245, 158, 11, 0.12)',
    border: '#FCEBD1',
    borderStrong: '#FDE68A',
    borderSoft: 'rgba(245, 158, 11, 0.10)',
    separator: 'rgba(245, 158, 11, 0.12)',
    separatorStrong: 'rgba(245, 158, 11, 0.20)',
    chip: '#FEF3C7',
    chipText: '#B45309',
  }),
  teacher: makeRoleTheme({
    bg: '#F1FEF7',
    bgSoft: '#E1FDEE',
    bgStrong: '#D1FCE5',
    accent: '#10B981',
    accentSoft: '#D1FAE5',
    accentStrong: '#047857',
    highlight: '#8B5CF6',
    highlightSoft: '#EDE9FE',
    surface: '#FFFFFF',
    surfaceMuted: '#F6FEF9',
    surfaceRaised: '#FCFFFD',
    surfaceTint: '#ECFDF5',
    surfaceSoft: '#D1FAE5',
    surfaceGlow: 'rgba(16, 185, 129, 0.12)',
    border: '#D1FCE5',
    borderStrong: '#A7F3D0',
    borderSoft: 'rgba(16, 185, 129, 0.10)',
    separator: 'rgba(16, 185, 129, 0.12)',
    separatorStrong: 'rgba(16, 185, 129, 0.20)',
    chip: '#D1FAE5',
    chipText: '#047857',
  }),
  admin: makeRoleTheme({
    bg: '#F7F1FE',
    bgSoft: '#EEE1FD',
    bgStrong: '#E5D1FC',
    accent: '#8B5CF6',
    accentSoft: '#EDE9FE',
    accentStrong: '#6D28D9',
    highlight: '#10B981',
    highlightSoft: '#D1FAE5',
    surface: '#FFFFFF',
    surfaceMuted: '#FAF6FE',
    surfaceRaised: '#FDFCFE',
    surfaceTint: '#F5F3FF',
    surfaceSoft: '#EDE9FE',
    surfaceGlow: 'rgba(139, 92, 246, 0.12)',
    border: '#E5D1FC',
    borderStrong: '#DDD6FE',
    borderSoft: 'rgba(139, 92, 246, 0.10)',
    separator: 'rgba(139, 92, 246, 0.12)',
    separatorStrong: 'rgba(139, 92, 246, 0.20)',
    chip: '#EDE9FE',
    chipText: '#6D28D9',
  }),
  payments: makeRoleTheme({
    bg: '#F1F2FE',
    bgSoft: '#E1E4FD',
    bgStrong: '#D1D6FC',
    accent: '#6366F1',
    accentSoft: '#E0E7FF',
    accentStrong: '#4338CA',
    highlight: '#F43F5E',
    highlightSoft: '#FFE4E6',
    surface: '#FFFFFF',
    surfaceMuted: '#F6F7FE',
    surfaceRaised: '#FCFCFF',
    surfaceTint: '#EEF2FF',
    surfaceSoft: '#E0E7FF',
    surfaceGlow: 'rgba(99, 102, 241, 0.12)',
    border: '#D1D6FC',
    borderStrong: '#C7D2FE',
    borderSoft: 'rgba(99, 102, 241, 0.10)',
    separator: 'rgba(99, 102, 241, 0.12)',
    separatorStrong: 'rgba(99, 102, 241, 0.20)',
    chip: '#E0E7FF',
    chipText: '#4338CA',
  }),
};

export const appRoleMeta = {
  student: {
    label: 'Student',
    shell: 'student',
    ...roleThemes.student,
  },
  parent: {
    label: 'Parent',
    shell: 'parent',
    ...roleThemes.parent,
  },
  teacher: {
    label: 'Teacher',
    shell: 'teacher',
    ...roleThemes.teacher,
  },
  admin: {
    label: 'Admin',
    shell: 'admin',
    ...roleThemes.admin,
  },
  payments: {
    label: 'Payments',
    shell: 'payments',
    ...roleThemes.payments,
  },
};

export const supportedRoles = Object.freeze(Object.keys(appRoleMeta));

export function getDashboardTheme(mode) {
  return dashboardThemes[mode] || dashboardThemes.midnight;
}

export function getRolePalette(role) {
  return roleThemes[role] || roleThemes.student;
}
